"""Bound work per interactive request; no automatic paid request retries."""
MAX_QUESTION_CHARACTERS = 4000
MAX_TITLE_CHARACTERS = 80
MAX_ANSWER_TOKENS = 1000
MAX_REWRITE_TOKENS = 256
MODEL_TIMEOUT_SECONDS = 20.0
EMBEDDING_TIMEOUT_SECONDS = 10.0
REWRITE_TIMEOUT_SECONDS = 10.0
